### ISSUE TITLE
How do I get skeleton code?

### ISSUE THREAD

**Issue by fadli0029** [PKUFlyingPig/CS61B#1]
Hi,

So for a given Lab/Project/HW, most of them have skeleton code that we need to pull. Assuming the gradescope autograder has been made public, I expected that the skeleton source code also does not require a ucberkeley credentials to access it. However, I can't find the skeleton code for any of the Lab/Project/Hw. How do you get it? (I know i can just pull yours, but I want fresh skeleton code)

Thanks!

**Comment by PKUFlyingPig** [comment]
The [skeleton source code repo](https://github.com/Berkeley-CS61B/skeleton-sp18.git) is public. In fact, if you read **part D** in [lab guide](https://sp18.datastructur.es/materials/lab/lab1/lab1) carefully, you will find that you don't need UC Berkeley credentials to access it. What the guide actually means is that you can create a personal private repo, then add the skeleton repo as a remote repo and pull the skeleton code into your private repo, then do all the remaining things in your private repo, which makes your solution private.

**Comment by fadli0029** [comment]
Bruh, how did i overlooked that lol. Thanks man! You're the goat
