### ISSUE TITLE
Nothing in the hw2.

### ISSUE THREAD

**Issue by zoubaobao** [PKUFlyingPig/CS61B#2]
Greetings! The Percolation file in "hw2" document is just skeleton file. There aren't any codes in that file. I wonder if you can make it public for us to learn. Thank you so much!

**Comment by PKUFlyingPig** [comment]
The percolation homework happens to be the same as Princeton's Algorithm Course's homework. You can reference to my solution [in this repo](https://github.com/PKUFlyingPig/Princeton-Algorithm).

**Comment by zoubaobao** [comment]
> The percolation homework happens to be the same as Princeton's Algorithm Course's homework. You can refer to my solution [in this repo](https://github.com/PKUFlyingPig/Princeton-Algorithm).

It's very kind of you. Thank you.
